application: webrtcing
version: 1
runtime: go
api_version: go1

handlers:
- url: /build
  static_dir: build
- url: /javascript
  static_dir: public/javascript
- url: /images
  static_dir: public/images
- url: /stylesheets
  static_dir: public/stylesheets
- url: /(.*\.html)
  static_files: public/\1
  upload: public/(.*\.html)

- url: /.*
  script: _go_app

inbound_services:
- channel_presence

