application: webrtcgame
version: live
runtime: go
api_version: go1

handlers:
# Static
- url: /javascript
  static_dir: public/javascript
  expiration: '1d'
- url: /images
  static_dir: public/images
  expiration: '1d'
- url: /dmaf__assets
  static_dir: public/dmaf__assets
  expiration: '1d'
- url: /lang
  static_dir: public/lang
  expiration: '1d'
- url: /fonts
  static_dir: public/fonts
  expiration: '1d'
- url: /stylesheets
  static_dir: public/stylesheets
  expiration: '1d'
- url: /favicon.ico
  static_files: public/images/favicon.ico
  upload: public/favicon.ico
  expiration: '7d'
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
- url: /(.*\.html)
  static_files: public/\1
  upload: public/(.*\.html)

# Tasks
- url: /_expire
  script: _go_app
  login: admin

# Rooms
- url: /.*
  script: _go_app
  # TODO enable this when going live, messy while developing
  secure: always
  # TODO require login on /xyz but not /_ah/*
  # login: admin

inbound_services:
- channel_presence

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?node_modules/.*$
- ^(.*/)?components/.*$
- ^(.*/)?lib/.*$
- ^(.*/)?test/.*$
- ^(.*/)?ui/.*$

pagespeed:
  domains_to_rewrite:
  - www.cubeslam.com
  - https://www.cubeslam.com
  disabled_rewriters:
  - LazyloadImages
  - lazyload_images
