application: einarsgame
version: 1
runtime: go
api_version: go1

handlers:
# Static
- url: /javascript
  static_dir: public/javascript
- url: /images
  static_dir: public/images
- url: /dmaf__assets
  static_dir: public/dmaf__assets
- url: /lang
  static_dir: public/lang
- url: /fonts
  static_dir: public/fonts
- url: /stylesheets
  static_dir: public/stylesheets
- url: /swf
  static_dir: public/swf
- url: /favicon.ico
  static_files: public/images/favicon.ico
  upload: public/favicon.ico
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
- url: /(.*\.html)
  static_files: public/\1
  upload: public/(.*\.html)

# Tasks
- url: /_expire
  script: _go_app
  login: admin

# Rooms
- url: /.*
  script: _go_app
  # TODO enable this when going live, messy while developing
  secure: always
  # TODO require login on /xyz but not /_ah/*
  # login: admin

inbound_services:
- channel_presence

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?node_modules/.*$
- ^(.*/)?components/.*$
- ^(.*/)?lib/.*$
- ^(.*/)?test/.*$
- ^(.*/)?ui/.*$
